export { default as Navbar } from './Navbar';
export { default as Home } from './Home';
export { default as Projects } from './Projects';
export { default as Skills } from './Skills';
export { default as SkillPage } from './Skill/SkillPage';
export { default as Contact } from './Contact';
export { default as Resume } from './Resume';
export { default as NotFound } from './NotFound';
export { default as TakeArtToHeart } from './Project/TakeArtToHeart/TakeArttoHeart';
export { default as ECommercePlatform } from './Project/ECommercePlatform/ECommercePlatform';
export { default as TaskManagementApp } from './Project/TaskManagementApp/TaskManagementApp';
export { default as WeatherDashboard } from './Project/WeatherDashboard/WeatherDashboard';
export { default as PortfolioWebsite } from './Project/PortfolioWebsite/PortfolioWebsite';
export { default as SocialMediaDashboard } from './Project/SocialMediaDashboard/SocialMediaDashboard';
export { default as FitnessTrackingApp } from './Project/FitnessTrackingApp/FitnessTrackingApp';
export { default as ProjectDetail } from './Project/ProjectDetail';
// export { default as Footer } from './Footer';